# Generated by Django 2.0 on 2018-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last', models.CharField(blank=True, default='%s', max_length=128, verbose_name='Your name:')),
                ('shabbat_dinner', models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend Shabbat dinner on Friday, July 20th?\n\n')),
                ('welcome_dinner', models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend the welcome dinner on Sunday, July 22nd?\n\n')),
                ('welcome_dietary_restrictions', models.CharField(blank=True, choices=[('None', 'None'), ('Veggie', 'Vegetarian'), ('Vegan', 'Vegan'), ('GF', 'Gluten-free'), ('Kosh', 'No meat with milk'), ('Other', 'Other (please elaborate in comments section)')], default='1', max_length=6, verbose_name='\nDo you have any dietary restrictions?\n\n')),
                ('wedding', models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend the wedding on Monday, July 23rd?\n\n')),
                ('wedding_meal', models.CharField(blank=True, choices=[('malfatti', 'Ricotta and spinach malfatti with sage butter and parmesan crisps (vegetarian)'), ('curry', 'Red lentil coconut curry, grilled sweetcorn and courgette, and crisp rice balls (vegan)')], default=None, max_length=2, verbose_name='\nAt the wedding, I would like to eat:\n\n')),
                ('tues_am', models.NullBooleanField(default=None, verbose_name='\nWill you be able to come to brunch on Tuesday, July 24th?\n\n')),
                ('tues_pm', models.NullBooleanField(default=None, verbose_name='\nWill you be able to come to the gathering on Tuesday, July 24th?\n\n')),
                ('song_request', models.TextField(blank=True, default='YMCA by The Village People', max_length=2048, verbose_name='I would dance if I heard this song:')),
                ('comments', models.TextField(blank=True, default="I'm so excited to come!", max_length=2048, verbose_name='Comments for the couple!')),
            ],
        ),
        migrations.CreateModel(
            name='RSVPFirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
