# Generated by Django 2.0 on 2018-02-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('shabbat_dinner', models.NullBooleanField(default=None)),
                ('welcome_dinner', models.BooleanField(default=False)),
                ('welcome_meal', models.TextField()),
                ('wedding', models.NullBooleanField(default=None)),
                ('wedding_meal', models.TextField()),
                ('tues_am', models.NullBooleanField(default=None)),
                ('tues_pm', models.NullBooleanField(default=None)),
                ('is_child', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('shabbat_dinner', models.NullBooleanField(default=None)),
                ('welcome_dinner', models.BooleanField(default=False)),
                ('wedding', models.NullBooleanField(default=None)),
                ('tues_am', models.NullBooleanField(default=None)),
                ('tues_pm', models.NullBooleanField(default=None)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
