# Generated by Django 2.0 on 2018-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='wedding_app',
            field=models.CharField(blank=True, choices=[('artichoke', 'Warm artichoke tart with tarragon and chervil dressing'), ('beets', 'Salad of baked golden & candy beetroot, hazelnut gremolata & gorgonzola')], default='artichoke', max_length=200, verbose_name='\nAt the wedding, I would like my appetizer to be:\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding_meal',
            field=models.CharField(blank=True, choices=[('malfatti', 'Ricotta and spinach malfatti with sage butter and parmesan crisps (vegetarian)'), ('curry', 'Red lentil coconut curry, grilled sweetcorn and courgette, and crisp rice balls (vegan)')], default='malfatti', max_length=200, verbose_name='\nAt the wedding, I would like my main meal to be:\n\n'),
        ),
    ]
