# Generated by Django 2.0 on 2018-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPFirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='welcome_meal',
        ),
        migrations.AddField(
            model_name='guest',
            name='comments',
            field=models.CharField(blank=True, default="I'm so excited to come!", max_length=2048, verbose_name='Comments for the couple!'),
        ),
        migrations.AddField(
            model_name='guest',
            name='first_last',
            field=models.CharField(blank=True, default='%s', max_length=128, verbose_name='Your name:'),
        ),
        migrations.AddField(
            model_name='guest',
            name='song_request',
            field=models.TextField(blank=True, default='YMCA by The Village People', verbose_name='I would dance if I heard this song:'),
        ),
        migrations.AddField(
            model_name='guest',
            name='welcome_dietary_restrictions',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Veggie', 'Vegetarian'), ('Vegan', 'Vegan'), ('GF', 'Gluten-free'), ('Kosh', 'No meat with milk'), ('Other', 'Other (please elaborate in comments section)')], default='1', max_length=6, verbose_name='\nDo you have any dietary restrictions?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='shabbat_dinner',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend Shabbat dinner on Friday, July 20th?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tues_am',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to come to brunch on Tuesday, July 24th?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tues_pm',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to come to the gathering on Tuesday, July 24th?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend the wedding on Monday, July 23rd?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding_meal',
            field=models.CharField(blank=True, choices=[('malfatti', 'Ricotta and spinach malfatti with sage butter and parmesan crisps'), ('curry', 'Red lentil coconut curry, grilled sweetcorn and courgette, and crisp rice balls')], default=None, max_length=2, verbose_name='\nAt the wedding, I would like to eat:\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='welcome_dinner',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend the welcome dinner on Sunday, July 22nd?\n\n'),
        ),
    ]
