# Generated by Django 2.0 on 2018-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0002_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='welcome_meal',
        ),
        migrations.AddField(
            model_name='guest',
            name='welcome_dietary_restrictions',
            field=models.CharField(choices=[('1', 'None'), ('2', 'Vegetarian'), ('3', 'Vegan'), ('4', 'Gluten-free'), ('5', 'No meat with milk'), ('6', 'Other')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding_meal',
            field=models.CharField(choices=[('1', 'Ricotta and spinach malfatti with sage butter and parmesan crisps'), ('2', 'Red lentil coconut curry, grilled sweetcorn and courgette, and crisp rice balls')], max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='welcome_dinner',
            field=models.NullBooleanField(default=None),
        ),
    ]
