# Generated by Django 2.0 on 2018-02-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0003_auto_20180206_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPFirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding_meal',
            field=models.CharField(choices=[('1', 'Ricotta and spinach malfatti with sage butter and parmesan crisps'), ('2', 'Red lentil coconut curry, grilled sweetcorn and courgette, and crisp rice balls')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='welcome_dietary_restrictions',
            field=models.CharField(choices=[('1', 'None'), ('2', 'Vegetarian'), ('3', 'Vegan'), ('4', 'Gluten-free'), ('5', 'No meat with milk'), ('6', 'Other')], default='1', max_length=6),
        ),
        migrations.AddField(
            model_name='guest',
            name='first_last',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='weddingsite.RSVPFirstModel'),
        ),
    ]
