# Generated by Django 2.0 on 2018-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0004_auto_20180207_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpfirstmodel',
            name='your_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
