# Generated by Django 2.0 on 2018-02-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0005_auto_20180208_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_last',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddingsite.RSVPFirstModel'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding_meal',
            field=models.CharField(blank=True, choices=[('1', 'Ricotta and spinach malfatti with sage butter and parmesan crisps'), ('2', 'Red lentil coconut curry, grilled sweetcorn and courgette, and crisp rice balls')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='welcome_dietary_restrictions',
            field=models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Vegetarian'), ('3', 'Vegan'), ('4', 'Gluten-free'), ('5', 'No meat with milk'), ('6', 'Other')], default='1', max_length=6),
        ),
    ]
