# Generated by Django 2.0 on 2018-02-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0006_auto_20180208_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='comments',
            field=models.TextField(blank=True, verbose_name='\nComments for the couple!\n'),
        ),
        migrations.AddField(
            model_name='guest',
            name='song_request',
            field=models.TextField(blank=True, verbose_name='\nI would dance if I heard this song:\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='shabbat_dinner',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend Shabbat dinner on Friday, July 20th?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tues_am',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to come to brunch on Tuesday, July 24th?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tues_pm',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to come to the gathering on Tuesday, July 24th?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend the wedding on Monday, July 23rd?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wedding_meal',
            field=models.CharField(blank=True, choices=[('1', 'Ricotta and spinach malfatti with sage butter and parmesan crisps'), ('2', 'Red lentil coconut curry, grilled sweetcorn and courgette, and crisp rice balls')], default='1', max_length=2, verbose_name='\nAt the wedding, I would like to eat:\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='welcome_dietary_restrictions',
            field=models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Vegetarian'), ('3', 'Vegan'), ('4', 'Gluten-free'), ('5', 'No meat with milk'), ('6', 'Other (please elaborate in comments section)')], default='1', max_length=6, verbose_name='\nDo you have any dietary restrictions?\n\n'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='welcome_dinner',
            field=models.NullBooleanField(default=None, verbose_name='\nWill you be able to attend the welcome dinner on Sunday, July 22nd?\n\n'),
        ),
    ]
