# Generated by Django 2.0 on 2018-02-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingsite', '0007_auto_20180210_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_last',
            field=models.TextField(blank=True, default='%s', verbose_name='Your name:'),
        ),
    ]
